// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMH26d1fZPeFtXFw9dY7ANZteUFe2eOSc',
    appId: '1:205184761831:web:fee7a252117892db240742',
    messagingSenderId: '205184761831',
    projectId: 'inclass-18',
    authDomain: 'inclass-18.firebaseapp.com',
    storageBucket: 'inclass-18.firebasestorage.app',
    measurementId: 'G-TQQ3G2ZT5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzyVJ_4xtP2rAMVzxYpkedLSccn5UJdtc',
    appId: '1:205184761831:android:79f47d5c9d290fa2240742',
    messagingSenderId: '205184761831',
    projectId: 'inclass-18',
    storageBucket: 'inclass-18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmtI7C-UvjVhiPl3Adn8g2Zk0h84ozZFI',
    appId: '1:205184761831:ios:078a2b8406384012240742',
    messagingSenderId: '205184761831',
    projectId: 'inclass-18',
    storageBucket: 'inclass-18.firebasestorage.app',
    iosBundleId: 'com.example.inclass16',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmtI7C-UvjVhiPl3Adn8g2Zk0h84ozZFI',
    appId: '1:205184761831:ios:078a2b8406384012240742',
    messagingSenderId: '205184761831',
    projectId: 'inclass-18',
    storageBucket: 'inclass-18.firebasestorage.app',
    iosBundleId: 'com.example.inclass16',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMH26d1fZPeFtXFw9dY7ANZteUFe2eOSc',
    appId: '1:205184761831:web:ed25fed00bb419a6240742',
    messagingSenderId: '205184761831',
    projectId: 'inclass-18',
    authDomain: 'inclass-18.firebaseapp.com',
    storageBucket: 'inclass-18.firebasestorage.app',
    measurementId: 'G-1WJJP6XHR1',
  );
}
